name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace Mapbox token
        run: |
          sed -i 's|{{MAPBOX}}|'"$MAPBOX"'|g' ./map/index.html
          mv ./map/index.html ./map/home.html # Rename for cache refresh
          echo "Contents after replacement and renaming:"
          cat ./map/home.html
        env:
          MAPBOX: ${{ secrets.MAPBOX }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./map
