name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Replace tokens in home.html
      run: |
        echo "Replacing Mapbox and CloudKit tokens in home.html"
        sed -i "s|{{MAPBOX}}|$MAPBOX|g" ./map/home.html
        sed -i "s|{{APPLE}}|$APPLE|g" ./map/home.html
      env:
        MAPBOX: ${{ secrets.MAPBOX }}
        APPLE: ${{ secrets.APPLE }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./map
        publish_branch: gh-pages
        exclude_assets: .github
