name: Deploy to GitHub Pages on Main Branch

on:
  push:
    branches:
      - main  # Only trigger on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace tokens in home.html
        run: |
          sed -i 's|{{MAPBOX}}|'"$MAPBOX"'|g' map/home.html
          sed -i 's|{{APPLE}}|'"$CLOUDKIT_TOKEN"'|g' map/home.html
        env:
          MAPBOX: ${{ secrets.MAPBOX }}
          CLOUDKIT_TOKEN: ${{ secrets.CLOUDKIT_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add map/home.html
          git commit -m "Update tokens in home.html"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
