name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Replace placeholders in home.html with secrets
      - name: Replace tokens in home.html
        env:
          MAPBOX: ${{ secrets.MAPBOX }}
          APPLE: ${{ secrets.APPLE }}
        run: |
          echo "Replacing Mapbox token in home.html file"
          sed -i "s|{{MAPBOX}}|$MAPBOX|g" ./map/home.html
          echo "Replacing CloudKit token in home.html file"
          sed -i "s|{{APPLE}}|$APPLE|g" ./map/home.html
          
          # Display the updated file for verification
          cat ./map/home.html

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./map
          publish_branch: gh-pages
          exclude_assets: .github
