name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Replace Mapbox and CloudKit tokens in home.html
      run: |
        sed -i "s|{{MAPBOX}}|$MAPBOX|g" ./map/home.html
        sed -i "s|{{APPLE}}|$APPLE|g" ./map/home.html
      env:
        MAPBOX: ${{ secrets.MAPBOX_TOKEN }}
        APPLE: ${{ secrets.CLOUDKIT_TOKEN }}

    - name: Verify content in map directory
      run: ls -R ./map

    - name: Deploy to GitHub Pages
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add map/home.html
        git commit -m "Deploy updated home.html with tokens"
        git push origin main
