name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace Mapbox token
        run: |
          sed -i 's|{{MAPBOX}}|'"$MAPBOX"'|g' map/index.html
        env:
          MAPBOX: ${{ secrets.MAPBOX }}

      - name: Verify Mapbox token replacement
        run: |
          echo "Checking for Mapbox token replacement in index.html..."
          grep 'accessToken' map/index.html || echo "No accessToken found in map/index.html"
          cat map/index.html | grep 'accessToken'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./map
